#!/usr/bin/env python

def repo_paths(path):
    import mercurial.hg, mercurial.ui
    repo = mercurial.hg.repository(mercurial.ui.ui(), path)
    return repo.ui.configitems('paths')

def bitb_paths(paths):
    import re
    pattern = re.compile('bitbucket.org')
    paths = [pattern.search(path) for name, path in paths]
    return filter(None, paths)

def open(paths):
    import webbrowser
    if paths:
        url = 'http://' + paths[0].string[paths[0].start():]
        webbrowser.open(url)
    else:
        raise Exception('BitBucket path not found')

def main(paths):
    for path in paths:
        try:
            open(bitb_paths(repo_paths(path)))
        except Exception as err:
            print 'abort:', err

if __name__ == '__main__':
    import sys, os
    args = sys.argv[1:]
    if not args:
        args = [os.path.curdir]
    main(args)
