#!/usr/bin/env ruby -w
## See how specific formulas changed in the last `brew update`.
#
# Example:
#
#   $ brew update
#   $ brew-log git mongodb node redis hub
#   $ brew-log --diff hub

if ARGV.empty?
  puts "Usage: #{File.basename $0} <names>"
  exit(2)
else
  dir = `brew --prefix`.chomp

  args = ['diff']
  args << 'ORIG_HEAD..' << '--'
  args.concat ARGV.map { |name| "Library/Formula/#{name}.rb" }

  exec 'git', "--git-dir=#{dir}/.git", *args
end
