#!/bin/sh
# Usage: browser [<URL>...]
# Open each <URL> in a web browser.
# Without arguments, read HTML from stdin.

set -e

self () {
	local SELF="$(basename -- "$0")"
	case "$SELF" in
	web|browser)
		SELF="${BROWSER:-safari}"
		;;
	esac
	echo "$SELF"
}

if [ $# -eq 0 ]; then
	if [ -t 0 ]; then
		usage "$0"; exit
	fi
	set -- "$(to_tmp)"
fi
open -a "$(self)" "$@"
