#!/bin/sh
# Usage: fscript-inject <pid>...
# Inject FScript into the applications corresponding to each <pid>.

if [ $# -eq 0 ]; then
	usage "$0"; exit
fi

for proc; do
	gdb --pid "$proc" --batch --nx --command=/dev/stdin <<-GDB
		p (char)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScript.framework"] load]
		p (void)[FScriptMenuItem insertInMainMenu]
	GDB
done
