#!/bin/sh
# Usage: itunes <option>
# iTunes Command Line Control.
#
# Options:
#   status   = Shows iTunes' status, current artist and track.
#   play     = Start playing iTunes.
#   pause    = Pause iTunes.
#   next     = Go to the next track.
#   prev     = Go to the previous track.
#   rate #   = Set current track rating to # [0-100].
#              20-1 star, 40-2 stars, 60-3 stars, etc.
#   mute     = Mute iTunes' volume.
#   unmute   = Unmute iTunes' volume.
#   vol up   = Increase iTunes' volume by 10%
#   vol down = Increase iTunes' volume by 10%
#   vol #    = Set iTunes' volume to # [0-100]
#   stop     = Stop iTunes.
#   quit     = Quit iTunes.

####################################
# iTunes Command Line Control v1.0
# written by David Schlosnagle
# created 2001.11.08
####################################
# Modified by Bill Bumgarner
# <bbum@mac.com>
# 24-05-2008
#
# 1) updated to deal w/Leopard's sh
# 2) added ability to set rating
#    Ratings are 0-100
###################################

set -e

if [ $# -eq 0 ]; then
	usage "$0"; exit
fi

case $1 in
"status"  ) state=`osascript -e 'tell application "iTunes" to player state as string'`
	echo "iTunes is currently $state."
	if [ $state = "playing" ]; then
		artist=`osascript -e 'tell application "iTunes" to artist of current track as string'`
		track=`osascript -e 'tell application "iTunes" to name of current track as string'`
		rating=`osascript -e 'tell application "iTunes" to get rating of current track'`
		echo "$artist: $track (Rating: $rating)"
	fi
	;;

"play"    ) echo "Playing iTunes."
	osascript -e 'tell application "iTunes" to play'
	;;

"pause"   ) echo "Pausing iTunes."
	osascript -e 'tell application "iTunes" to pause'
	;;

"next"    ) echo "Going to next track."
	osascript -e 'tell application "iTunes" to next track'
	;;

"prev"    ) echo "Going to previous track."
	osascript -e 'tell application "iTunes" to previous track'
	;;

"rate"    ) echo "Setting rating on current track."
	osascript -e "tell application \"iTunes\" to set rating of current track to $2"
	;;

"mute"    ) echo "Muting iTunes volume level."
	osascript -e 'tell application "iTunes" to set mute to true'
	;;

"unmute"  ) echo "Unmuting iTunes volume level."
	osascript -e 'tell application "iTunes" to set mute to false'
	;;

"vol"     ) echo "Changing iTunes volume level."
	vol=`osascript -e 'tell application "iTunes" to sound volume as integer'`
	case $2 in
		"up")   newvol=`expr $vol + 10` ;;
		"down") newvol=`expr $vol - 10` ;;
		*)      newvol=$2               ;;
	esac
	osascript -e "tell application \"iTunes\" to set sound volume to $newvol"
	;;

"stop"    ) echo "Stopping iTunes."
	osascript -e 'tell application "iTunes" to stop'
	;;

"quit"    ) echo "Quitting iTunes."
	osascript -e 'tell application "iTunes" to quit'
	;;

"help" | *) echo "iTunes Command Line Control Help:"
	usage "$0"
	;;
esac
