#!/bin/sh
# Usage: newbin <script>
# Create <script> and make it executable.
# Pipe stdin into <script>, otherwise open it in EDITOR.

set -e

if [ $# -eq 0 ]; then
	usage "$0"; exit
fi

script="$*"
touch "$script"
chmod a+x "$script"
if [ -t 0 ]; then
	"${EDITOR:-vi}" "$script"
else
	cat >| "$script"
fi
