#!/usr/bin/env ruby -wKU
#
# Export Org files as HTML.
#

def usage
  $stderr.puts "Usage: #{File.basename($PROGRAM_NAME)} FILE ..."
  exit 255
end

usage  if ARGV.empty?

emacs_args = ['--batch', '--load', 'org']
ARGV.each { |e| emacs_args << '--visit' << e }
emacs_args << '--funcall' << 'org-export-as-html-batch'

system 'emacs', *emacs_args
