#!/usr/bin/env ruby -wKU -rubygems

require 'open-uri'

def read_public(name)
  URI("http://pastie.org/#{name}.txt").read
end

def read_private(url)
  require 'nokogiri'
  html = Nokogiri::HTML(open(url))
  url = html.at('a.utility')['href']
  URI(url).read
end

def fetch(arg)
  public_id = /^\d+$/
  base = File.basename(arg)
  return read_public(base)  if public_id =~ base
  read_private(URI(arg))
end

unless ARGV.length == 1
  puts "Usage: #{File.basename $PROGRAM_NAME} PASTE_ID | PASTE_URL"
  exit 2
end
puts fetch(ARGV.first)
