#!/usr/bin/env ruby -wKU

pathmap = Hash.new { |hash, key| hash[key] = [] }

ENV['PATH'].split(':').each do |path|
  if File.directory?(path)
    Dir.foreach(path) do |file|
      pathmap[file] << path  unless file =~ /^\./
    end
  end
end

pathmap.sort.each do |name, dirs|
  if dirs.length > 1
    puts "#{name} has #{dirs.length} entries:"
    dirs.each do |dir|
      puts "\t#{dir}"
    end
  end
end
