#!/usr/bin/env ruby -KU

require 'pathname'

args = ARGV.empty? ? ARGF : ARGV

args.each { |a|
  begin
    puts Pathname.new(a.chomp).realpath
  rescue StandardError => err
    puts "#{File.basename $PROGRAM_NAME}: #{err}"
  end
}
