#!/usr/bin/env python

'''Print the URL of the current document of Safari.app.'''

from appscript import app

def safari():
    return app('Safari')

def current_document(app = safari()):
    return app.documents[1].get()

def main():
    return [doc.URL.get() for doc in [current_document(safari())]]

if __name__ == '__main__':
    print '\n'.join(main())