#!/usr/bin/env ruby -wKU

def valid?(file, tests)
  ENV['file'] = file
  tests.each do |test|
    return true  if system(test)
  end
  false
end

def convert(test)
  # test arrives frozen, so no #<< for us
  test += ' "$file"'  unless test['$']
  test
end

def run(args, io)
  tests = args.map { |a| convert(a) }
  io.each { |file| puts file  if valid?(file.chomp, tests) }
end

if __FILE__ == $PROGRAM_NAME
  run(ARGV, $stdin)
end
