#!/bin/sh
# Usage: to_tmp
# Write stdin to a tmpfile, then print its name on stdout.

set -e

if [ $# -ne 0 ]; then
	usage "$0"; exit
fi

TMPFILE="$(mktemp -t to_tmp)"
cat >| "$TMPFILE"
echo "$TMPFILE"
