#!/bin/sh
# Usage: unquarantine <file>...
# Remove the "quarantine" extended attribute from each <file>.

set -e

if [ $# -eq 0 ]; then
	usage "$0"; exit
fi

/usr/bin/xattr -d com.apple.quarantine "$@"
