#!/usr/bin/env ruby -w

require 'uri'

def usage(msg= nil)
  name = File.basename($PROGRAM_NAME)
  puts "#{name}: #{msg}"  if msg
  puts "Usage: #{name} METHOD"
  exit 255
end

def meth(args)
  usage  unless args.length == 1
  symb = args.first.to_sym
  begin
    return URI.send(:method, symb)
  rescue NameError
    usage("undefined method: `#{symb}'")
  end
end

func = meth(ARGV)
$stdin.each { |line| puts func[line.chomp] }
