#!/bin/sh
# Usage: weasel [<file>...]
# Find and highlight "weasel words" in each <file>.
# Without arguments, read text from stdin.

set -e

weasels="many|various|very|fairly|several|extremely\
|exceedingly|quite|remarkably|few|surprisingly\
|mostly|largely|huge|tiny|((are|is) a number)\
|excellent|interestingly|significantly\
|substantially|clearly|vast|relatively|completely"

egrep -i -n --color "\\b($weasels)\\b" "$@"
