#!/usr/bin/env python
# Usage: which_app [<app>...]
# Locate each OS X application using LaunchServices.
# Applications can be specified by name or bundle identifier.
# Without arguments, read applications from stdin.

from LaunchServices import LSFindApplicationForInfo, kLSUnknownCreator

def find_app_by_id(id):
    return LSFindApplicationForInfo(kLSUnknownCreator, id, None, None, None)

def find_app_by_name(name):
    return LSFindApplicationForInfo(kLSUnknownCreator, None, name, None, None)

def find_app(app):
    ok, ref, url = find_app_by_id(app)
    if ok == 0:
        return ref.as_pathname()
    ok, ref, url = find_app_by_name(app)
    if ok == 0:
        return ref.as_pathname()
    ok, ref, url = find_app_by_name(app + '.app')
    if ok == 0:
        return ref.as_pathname()
    return None

def main(args):
    for app in args:
        path = find_app(app.strip())
        if path is not None:
            print path

if __name__ == '__main__':
    import sys
    args = sys.argv[1:]
    if not args:
        args = sys.stdin
    main(args)
